apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: weh3o8a8w-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: weh3o8a8w-nodejs 
  name: weh3o8a8w-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: weh3o8a8w-nodejs
    weight: 100 
